cacheFolder: ./.yarn/cache

cacheMigrationMode: always

deferredVersionFolder: ./.yarn/versions

enableGlobalCache: false

enableImmutableCache: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"
